apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels: 
      type: local 
   
spec:
  capacity:
   storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath: 
     path: /data

---

apiVersion: v1

kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany

  