apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  selector:
    matchLabels:
      app: mssql
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
   
        image: mcr.microsoft.com/mssql/server:2017-CU20-ubuntu-16.04
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "@Aa123456"
        volumeMounts:
        - name: mssql-pvc-claim
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-pvc-claim
        persistentVolumeClaim:
          claimName: mssql-pvc-claim 
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 30201
  type: NodePort